import type { PFDModel } from '@/types/pfd';

export const TEST_CASE_A: PFDModel = {
  id: 'TC-A',
  name: 'Storage Tank & Recirculation Pump Loop',
  revision: 'Rev.A',
  createdAt: new Date().toISOString(),

  equipment: [
    {
      id: 'T-101',
      tag: 'T-101',
      type: 'storage_tank',
      label: 'Feed Storage Tank',
      sequence: 0,
      x: 60,
      y: 240,
      width: 90,
      height: 110,
      material: 'SS316L',
      notes: ['Atmospheric Vessel', 'Capacity: TBD'],
    },
    {
      id: 'STR-101',
      tag: 'STR-101',
      type: 'strainer',
      label: 'Y-Strainer',
      sequence: 1,
      x: 248,
      y: 277,
      width: 32,
      height: 32,
      autoAdded: true,
      material: 'SS316L',
      notes: ['ENG-002 Auto-Added', '40 Mesh Screen'],
    },
    {
      id: 'P-101',
      tag: 'P-101',
      type: 'pump',
      label: 'Recirculation Pump',
      sequence: 2,
      x: 360,
      y: 265,
      width: 70,
      height: 70,
      material: 'SS316L',
      notes: ['Centrifugal Pump', 'API 610'],
    },
    {
      id: 'R-101',
      tag: 'R-101',
      type: 'reactor',
      label: 'Reactor 1',
      sequence: 4,
      x: 680,
      y: 130,
      width: 80,
      height: 110,
      material: 'SS316L',
      notes: ['CSTR', 'Controlled Flow'],
    },
    {
      id: 'R-102',
      tag: 'R-102',
      type: 'reactor',
      label: 'Reactor 2',
      sequence: 4,
      x: 680,
      y: 370,
      width: 80,
      height: 110,
      material: 'SS316L',
      notes: ['CSTR', 'Controlled Flow'],
    },
  ],

  instruments: [
    {
      id: 'LT-101',
      tag: 'LT-101',
      type: 'LT',
      label: 'Level Transmitter',
      x: 165,
      y: 216,
      equipmentRef: 'T-101',
      autoAdded: true,
    },
    {
      id: 'VENT-101',
      tag: 'VENT-101',
      type: 'vent',
      label: 'Atm. Vent',
      x: 95,
      y: 212,
      equipmentRef: 'T-101',
      autoAdded: true,
    },
    {
      id: 'PI-101',
      tag: 'PI-101',
      type: 'PI',
      label: 'Suction Pressure',
      x: 300,
      y: 232,
      lineRef: 'L-001',
    },
    {
      id: 'PI-102A',
      tag: 'PI-102A',
      type: 'PI',
      label: 'Discharge Pressure A',
      x: 490,
      y: 172,
      lineRef: 'L-002',
      autoAdded: true,
    },
    {
      id: 'PI-102B',
      tag: 'PI-102B',
      type: 'PI',
      label: 'Discharge Pressure B',
      x: 490,
      y: 398,
      lineRef: 'L-003',
      autoAdded: true,
    },
    {
      id: 'FIC-101',
      tag: 'FIC-101',
      type: 'FIC',
      label: 'Flow Controller R-101',
      x: 578,
      y: 172,
      lineRef: 'L-002',
      isFunctionBlock: true,
    },
    {
      id: 'FIC-102',
      tag: 'FIC-102',
      type: 'FIC',
      label: 'Flow Controller R-102',
      x: 578,
      y: 398,
      lineRef: 'L-003',
      isFunctionBlock: true,
    },
  ],

  pipes: [
    {
      id: 'L-001',
      tag: '3"-SS316L-L-001',
      from: 'T-101',
      to: 'P-101',
      size: '3"',
      material: 'SS316L',
      type: 'process',
      points: [
        [150, 295],
        [248, 295],
        [280, 295],
        [360, 295],
      ],
      flowDirection: 'forward',
    },
    {
      id: 'L-002',
      tag: '2"-SS316L-L-002',
      from: 'P-101',
      to: 'R-101',
      size: '2"',
      material: 'SS316L',
      type: 'process',
      points: [
        [430, 280],
        [470, 280],
        [470, 190],
        [680, 190],
      ],
      flowDirection: 'forward',
    },
    {
      id: 'L-003',
      tag: '2"-SS316L-L-003',
      from: 'P-101',
      to: 'R-102',
      size: '2"',
      material: 'SS316L',
      type: 'process',
      points: [
        [430, 310],
        [470, 310],
        [470, 425],
        [680, 425],
      ],
      flowDirection: 'forward',
    },
    {
      id: 'L-004',
      tag: '2"-SS316L-L-004-BYP',
      from: 'FIC-101-bypass',
      to: 'FIC-101-bypass',
      size: '2"',
      material: 'SS316L',
      type: 'bypass',
      points: [
        [570, 190],
        [570, 155],
        [650, 155],
        [650, 190],
      ],
      flowDirection: 'forward',
      autoAdded: true,
    },
    {
      id: 'L-005',
      tag: '2"-SS316L-L-005-BYP',
      from: 'FIC-102-bypass',
      to: 'FIC-102-bypass',
      size: '2"',
      material: 'SS316L',
      type: 'bypass',
      points: [
        [570, 425],
        [570, 460],
        [650, 460],
        [650, 425],
      ],
      flowDirection: 'forward',
      autoAdded: true,
    },
    {
      id: 'L-006',
      tag: '1"-SS316L-L-006-VENT',
      from: 'T-101',
      to: 'ATM',
      size: '1"',
      material: 'SS316L',
      type: 'vent',
      points: [
        [105, 240],
        [105, 192],
      ],
      flowDirection: 'forward',
      autoAdded: true,
    },
  ],

  controlValves: [
    {
      id: 'CV-101',
      tag: 'FCV-101',
      x: 619,
      y: 175,
      lineRef: 'L-002',
      hasBypass: true,
      bypassLineId: 'L-004',
    },
    {
      id: 'CV-102',
      tag: 'FCV-102',
      x: 619,
      y: 420,
      lineRef: 'L-003',
      hasBypass: true,
      bypassLineId: 'L-005',
    },
  ],

  validationResults: [],
};

export const TEST_CASE_B: PFDModel = {
  id: 'TC-B',
  name: 'Distillation Column Feed System',
  revision: 'Rev.A',
  createdAt: new Date().toISOString(),
  equipment: [
    {
      id: 'V-201',
      tag: 'V-201',
      type: 'vessel',
      label: 'Feed Drum',
      sequence: 0,
      x: 60,
      y: 230,
      width: 90,
      height: 100,
      material: 'CS',
      notes: ['Atmospheric', 'Feed Buffer'],
    },
    {
      id: 'STR-201',
      tag: 'STR-201',
      type: 'strainer',
      label: 'Basket Strainer',
      sequence: 1,
      x: 248,
      y: 269,
      width: 32,
      height: 32,
      autoAdded: true,
      material: 'CS',
      notes: ['ENG-002 Auto-Added'],
    },
    {
      id: 'P-201',
      tag: 'P-201',
      type: 'pump',
      label: 'Feed Pump',
      sequence: 2,
      x: 360,
      y: 260,
      width: 70,
      height: 70,
      material: 'CS',
      notes: ['Centrifugal', 'API 610'],
    },
    {
      id: 'E-201',
      tag: 'E-201',
      type: 'heat_exchanger',
      label: 'Feed/Btm Exchanger',
      sequence: 3,
      x: 560,
      y: 240,
      width: 100,
      height: 70,
      material: 'CS',
      notes: ['Shell & Tube', 'TEMA-R'],
    },
    {
      id: 'T-201',
      tag: 'T-201',
      type: 'storage_tank',
      label: 'Distillation Column',
      sequence: 4,
      x: 760,
      y: 130,
      width: 80,
      height: 220,
      material: 'CS',
      notes: ['Distillation Column', '20 Trays'],
    },
  ],
  instruments: [
    {
      id: 'LT-201',
      tag: 'LT-201',
      type: 'LT',
      label: 'Feed Drum Level',
      x: 165,
      y: 210,
      equipmentRef: 'V-201',
      autoAdded: true,
    },
    {
      id: 'VENT-201',
      tag: 'VENT-201',
      type: 'vent',
      label: 'Atm. Vent',
      x: 95,
      y: 206,
      equipmentRef: 'V-201',
      autoAdded: true,
    },
    {
      id: 'PI-201',
      tag: 'PI-201',
      type: 'PI',
      label: 'Suction PI',
      x: 300,
      y: 240,
      lineRef: 'L-201',
    },
    {
      id: 'PI-202',
      tag: 'PI-202',
      type: 'PI',
      label: 'Discharge PI',
      x: 460,
      y: 250,
      lineRef: 'L-202',
      autoAdded: true,
    },
    {
      id: 'FIC-201',
      tag: 'FIC-201',
      type: 'FIC',
      label: 'Feed Flow Controller',
      x: 528,
      y: 250,
      lineRef: 'L-202',
      isFunctionBlock: true,
    },
    {
      id: 'LT-202',
      tag: 'LT-202',
      type: 'LT',
      label: 'Column Level',
      x: 855,
      y: 210,
      equipmentRef: 'T-201',
      autoAdded: true,
    },
    {
      id: 'VENT-202',
      tag: 'VENT-202',
      type: 'vent',
      label: 'Column Vent',
      x: 795,
      y: 106,
      equipmentRef: 'T-201',
      autoAdded: true,
    },
  ],
  pipes: [
    {
      id: 'L-201',
      tag: '4"-CS-L-201',
      from: 'V-201',
      to: 'P-201',
      size: '4"',
      material: 'CS',
      type: 'process',
      points: [[150, 285], [248, 285], [280, 285], [360, 285]],
      flowDirection: 'forward',
    },
    {
      id: 'L-202',
      tag: '3"-CS-L-202',
      from: 'P-201',
      to: 'E-201',
      size: '3"',
      material: 'CS',
      type: 'process',
      points: [[430, 295], [560, 295]],
      flowDirection: 'forward',
    },
    {
      id: 'L-203',
      tag: '3"-CS-L-203',
      from: 'E-201',
      to: 'T-201',
      size: '3"',
      material: 'CS',
      type: 'process',
      points: [[660, 275], [760, 275]],
      flowDirection: 'forward',
    },
    {
      id: 'L-204',
      tag: '3"-CS-L-204-BYP',
      from: 'FIC-201-bypass',
      to: 'FIC-201-bypass',
      size: '3"',
      material: 'CS',
      type: 'bypass',
      points: [[520, 295], [520, 255], [600, 255], [600, 295]],
      flowDirection: 'forward',
      autoAdded: true,
    },
    {
      id: 'L-205',
      tag: '2"-CS-L-205-VENT',
      from: 'V-201',
      to: 'ATM',
      size: '2"',
      material: 'CS',
      type: 'vent',
      points: [[105, 230], [105, 186]],
      flowDirection: 'forward',
      autoAdded: true,
    },
  ],
  controlValves: [
    {
      id: 'CV-201',
      tag: 'FCV-201',
      x: 500,
      y: 290,
      lineRef: 'L-202',
      hasBypass: true,
      bypassLineId: 'L-204',
    },
  ],
  validationResults: [],
};
